### ISSUE TITLE
setExit() "wrapper" in Other.lua does not pass some valid exit strings to system one

### ISSUE THREAD

**Issue by SlySven** [vadi2/mudlet-lua#12]
Chris (I think) added `TLuaInterpreter::dirToNumber()` that would identify the exit direction code from the whole word as well as the initials (and or course the number directly), e.g. it should accept `"west"` as well as `"w"` or `3` to specify the west exit. **However the `setExit(fromRoomId, toRoomId, exitDirect)` in Other.lua was not updated (or removed) and so it blocks the full word form from being passed to the built-in one that it overrides.**

_I was doing some debugging and needed a map which I generated from code and was mystified why I could not get exits to be built between the rooms; as I was running in the IDE I set a breakpoint at the start of the `TLuaInterpreter::setExit()` but it was never hit.  It took me a while to figure out that there was something in the external lua files that was intercepting the calls my script was making - and if I hadn't added the lua files to the "other" project files variable in the Qt project file over a year ago I would not have found this out by doing a project wide search for `setExit`._

Given that I am retrofitting "nil + error messages" and doing other tidying up things to built in lua commands as I hit them I was amazed to see how many commands have got "wrappers" in these files which you have split off into a separate sub-project - what is starting to worry me is how many changes I have made that are being effectively filtered out by this intermediate layer!

**Comment by vadi2** [comment]
Yes, it added support for actually using words instead of having to use numbers like that was the case before. You can use debug.getinfo(functionname) to find out where a function is defined - happy to remove these fixer functions now that the core ones are being improved.

**Comment by vadi2** [comment]
This issue was moved to Mudlet/Mudlet#835
