### ISSUE TITLE
./mudlet-lua/lua/LuaGlobal.lua has been revised in main Mudlet  repository but not here

### ISSUE THREAD

**Issue by SlySven** [vadi2/mudlet-lua#13]
In https://github.com/Mudlet/Mudlet/pull/284 to the main repository (development branch) further changes were made to the code at the end of the referred to LuaGlobal.lua, it is approximately 4.5 Kbytes (the main repository still has a different "all-in-one" file (68K) with the **same** name in the _root_ of the main source code directory BTW!)

_Note also that:_  that PR was not copied over into the release_30 branch but even that differs (it also tries multiple prefixes to try and locate where the mudlet-lua & geyser files are) compared to the single location coded into the LuaGlobal.lua file here (and also has that rogue duplicate).

I think the version here needs revising - but which branch in the main repo does the code here apply to? :stuck_out_tongue_winking_eye:

**Comment by vadi2** [comment]
That change is only in the development branch, we'll get it in when we are merging release_30 into development.
