### ISSUE TITLE
GUIUtills has a pending revision in the main Mudlet repository

### ISSUE THREAD

**Issue by SlySven** [vadi2/mudlet-lua#15]
I am promulgating https://github.com/Mudlet/Mudlet/pull/374 which removed some spam output to the Central Debug Console which is coming about because the C++ core implementation of `deselect(...)` is being defeated/overridden by the version of this function in that repository's `GUIUtils.lua` file.  My PR included the complete commenting out of that file in that revision and if accepted will need the same change to be made on the "production" version of the Lua code stored here...

@vadi2 I have also tweaked (in a back-ward compatible way) the colour table defined in the same file - see https://github.com/Mudlet/Mudlet/pull/376 .

**Comment by vadi2** [comment]
Done - changes from release_30 have been applied here.
